var gulp = require('gulp');
var babel = require("gulp-babel");
var concat = require('gulp-concat');
var rename = require('gulp-rename');
var uglify = require('gulp-uglify');
var header = require('gulp-header');
var mergeStream = require('merge-stream');

gulp.task("default", function() {
  var libs = gulp
    .src([
      'lib/paper.js',
      'lib/SAT.js',
      'lib/base64-arraybuffer.js',
      'lib/convert-range.js',
      'lib/croquis.js',
      'lib/esprima.js',
      'lib/floodfill.min.js',
      'lib/howler.js',
      'lib/invert.min.js',
      'lib/is-var-name.js',
      'lib/jquery-3.3.1.min.js',
      'lib/jquery.pressure.js',
      'lib/jquery.mousewheel.js',
      'lib/jszip.js',
      'lib/lerp.js',
      'lib/platform.js',
      'lib/potrace.js',
      'lib/reserved-words.js',
      'lib/timestamp.js',
      'lib/soundcloud-waveform.js',
      'lib/Tween.js',
      'lib/uuid.js'
    ]);

  var src = gulp
    .src([
      'src/Wick.js',
      'src/Clipboard.js',
      'src/FileCache.js',
      'src/History.js',
      'src/ObjectCache.js',
      'src/Transformation.js',
      'src/ToolSettings.js',
      'src/ObjectCache.js',
      'src/Transformation.js',
      'src/GlobalAPI.js',
      'src/export/AudioTrack.js',
      'src/export/WickFile.js',
      'src/export/WickFile.Alpha.js',
      'src/base/Base.js',
      'src/base/Layer.js',
      'src/base/Project.js',
      'src/base/Selection.js',
      'src/base/Timeline.js',
      'src/base/Tween.js',
      'src/base/Path.js',
      'src/base/asset/Asset.js',
      'src/base/asset/FileAsset.js',
      'src/base/asset/ImageAsset.js',
      'src/base/asset/ClipAsset.js',
      'src/base/asset/SoundAsset.js',
      'src/base/asset/FontAsset.js',
      'src/base/Tickable.js',
      'src/base/Frame.js',
      'src/base/Clip.js',
      'src/base/clip/Button.js',
      'src/tools/Tool.js',
      'src/tools/Brush.js',
      'src/tools/Cursor.js',
      'src/tools/Ellipse.js',
      'src/tools/Eraser.js',
      'src/tools/Eyedropper.js',
      'src/tools/FillBucket.js',
      'src/tools/Interact.js',
      'src/tools/Line.js',
      'src/tools/None.js',
      'src/tools/Pan.js',
      'src/tools/PathCursor.js',
      'src/tools/Pencil.js',
      'src/tools/Rectangle.js',
      'src/tools/Text.js',
      'src/tools/Zoom.js',
      'src/view/paper-ext/Layer.erase.js',
      'src/view/paper-ext/Layer.hole.js',
      'src/view/paper-ext/Paper.OrderingUtils.js',
      'src/view/paper-ext/Paper.SelectionWidget.js',
      'src/view/paper-ext/Paper.SelectionBox.js',
      'src/view/paper-ext/Path.potrace.js',
      'src/view/paper-ext/TextItem.edit.js',
      'src/view/paper-ext/View.pressure.js',
      'src/view/paper-ext/View.gestures.js',
      'src/view/paper-ext/View.scrollToZoom.js',
      'src/view/View.js',
      'src/view/View.Project.js',
      'src/view/View.Selection.js',
      'src/view/View.Clip.js',
      'src/view/View.Button.js',
      'src/view/View.Timeline.js',
      'src/view/View.Layer.js',
      'src/view/View.Frame.js',
      'src/view/View.Path.js',
      'src/gui/GUIElement.js',
      'src/gui/GUIElement.Clickable.js',
      'src/gui/GUIElement.Draggable.js',
      'src/gui/GUIElement.AddFrameOverlay.js',
      'src/gui/GUIElement.Breadcrumbs.js',
      'src/gui/GUIElement.BreadcrumbsButton.js',
      'src/gui/GUIElement.CreateLayerLabel.js',
      'src/gui/GUIElement.Frame.js',
      'src/gui/GUIElement.FrameEdge.js',
      'src/gui/GUIElement.FrameGhost.js',
      'src/gui/GUIElement.FrameLeftEdge.js',
      'src/gui/GUIElement.FrameRightEdge.js',
      'src/gui/GUIElement.FramesContainer.js',
      'src/gui/GUIElement.FramesContainerBG.js',
      'src/gui/GUIElement.FramesStrip.js',
      'src/gui/GUIElement.LayerButton.js',
      'src/gui/GUIElement.LayerGhost.js',
      'src/gui/GUIElement.LayerHideButton.js',
      'src/gui/GUIElement.LayerLabel.js',
      'src/gui/GUIElement.LayerLockButton.js',
      'src/gui/GUIElement.LayersContainer.js',
      'src/gui/GUIElement.LayersContainerBG.js',
      'src/gui/GUIElement.LayerTweenButton.js',
      'src/gui/GUIElement.NumberLine.js',
      'src/gui/GUIElement.OnionSkinRange.js',
      'src/gui/GUIElement.OnionSkinRangeEnd.js',
      'src/gui/GUIElement.OnionSkinRangeStart.js',
      'src/gui/GUIElement.Playhead.js',
      'src/gui/GUIElement.Project.js',
      'src/gui/GUIElement.Scrollbar.js',
      'src/gui/GUIElement.ScrollbarGrabberHorizontal.js',
      'src/gui/GUIElement.ScrollbarGrabberVertical.js',
      'src/gui/GUIElement.ScrollbarHorizontal.js',
      'src/gui/GUIElement.ScrollbarVertical.js',
      'src/gui/GUIElement.SelectionBox.js',
      'src/gui/GUIElement.Timeline.js',
      'src/gui/GUIElement.TimelineAddFrameButton.js',
      'src/gui/GUIElement.TimelineDeleteLayerButton.js',
      'src/gui/GUIElement.Tween.js',
      'src/gui/GUIElement.TweenGhost.js',
    ])
    .pipe(header('/*Wick Engine https://github.com/Wicklets/wick-engine*/'))
    .pipe(babel());

  return mergeStream(libs, src)
    .pipe(concat('wickengine.js'))
    .pipe(gulp.dest('dist'));
});
